### ISSUE TITLE
[FR] ssh-ping exit code

### ISSUE THREAD

**Issue by gustaphe** [vaporup/ssh-tools#12]
It would be really nice if `ssh-ping` exited non-zero when all packets lost, like `ping` does.

That way you can do 

```bash
if ssh-ping -c1 -W3 host &>/dev/null
then
    something
fi
```

Right now, the condition is always true.

**Comment by vaporup** [comment]
The current version in master should do what you want.
Maybe it is time to do a new release :-)

**Comment by gustaphe** [comment]
My bad, I forgot to check which version I was on. Rookie mistake.

I'm installing though pacman, so a release would be nice.

(Thanks for a sweet piece of software)

**Comment by vaporup** [comment]
https://github.com/vaporup/ssh-tools/releases/tag/v1.7
