### ISSUE TITLE
Feature proposal: ssh-ping command should have an option to turn off output colors.

### ISSUE THREAD

**Issue by jk-1** [vaporup/ssh-tools#17]
Currently ssh-ping command has no switch to turn off colors.

    ssh-ping --help

    Usage: ssh-ping [OPTIONS] [user@]hostname

    OPTIONS:

        -4             Use IPv4 only
        -6             Use IPv6 only
        -c count       Stop after sending <count> request packets
        -F configfile  Specifies an alternative per-user configuration file.
                       If a configuration file is given on the command line,
                       the system-wide configuration file ( /etc/ssh/ssh_config ) will be ignored.
                       The default for the per-user configuration file is ~/.ssh/config.
        -h             Show this message
        -i interval    Wait <interval> seconds between sending each request.
                       The default is 1 second.
        -l user        Try login with <user> as username. The default is $USER.
        -D             Print timestamp (unix time + microseconds as in gettimeofday) before each line
        -H             Print timestamp (human readable) before each line
        -W timeout     Time to wait for a response, in seconds
        -p port        Port to connect to on the remote host.
                       This can be specified on a per-host basis in the configuration file.
        -q             Quiet output.
                       Nothing is displayed except the summary lines at startup time and when finished
        -v             Verbose output

Please add new option to turn off all colors etc ansi-escape codes.
- Light colors e.g. yellow are difficult to distinguish when using light terminal background
- Parsing of the command output is easier

**Comment by vaporup** [comment]
Hi jk-1,

which version are you using? The current release actually has an option for this already

**Comment by jk-1** [comment]
I noticed this problem in Ubuntu 20.04 and there the "default" version seems to be Version: 1.6-1.

I installed ssh-tools into a Ubuntu 22.04 host and it has Version: 1.7-2

And you are right, in the new version of ssh-ping there is option -n No colors, which does exactly what I needed.

So this issue can be closed. Thank you for your quick "fix".

**Comment by vaporup** [comment]
If you need the latest version on Ubuntu 20.04 also, you can use the deb file from 22.04 as well. Most of the time the packages are compatible with older Debian and Ubuntu versions.
